### ISSUE TITLE
thread 'main' panicked at 'Expected register: Unassigned', cranelift-codegen/src/ir/valueloc.rs:44:18

### ISSUE THREAD

**Issue by bjorn3** [CraneStation/cranelift#1002]
```
test compile
set is_pic
target x86_64-unknown-linux-gnu

function u0:0(i128, i128) -> i128 system_v {
    ss0 = explicit_slot 16 ; _0: u128 size=16 align=8,8

                                ebb0(v0: i128, v1: i128):
@0002                               v4 = iadd.i128 v0, v1
@0002                               v5 = stack_addr.i64 ss0
@0002                               store v4, v5
@0004                               v7 = load.i128 v5
@0004                               return v7
}
```

```
thread 'main' panicked at 'Expected register: Unassigned', cranelift-codegen/src/ir/valueloc.rs:44:18
stack backtrace:
[...]
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
   9: cranelift_codegen::ir::valueloc::ValueLoc::unwrap_reg
             at cranelift-codegen/src/ir/valueloc.rs:44
  10: cranelift_codegen::regalloc::coloring::Context::visit_inst
             at cranelift-codegen/src/regalloc/coloring.rs:620
  11: cranelift_codegen::regalloc::coloring::Context::visit_ebb
             at cranelift-codegen/src/regalloc/coloring.rs:193
  12: cranelift_codegen::regalloc::coloring::Context::run
             at cranelift-codegen/src/regalloc/coloring.rs:173
  13: cranelift_codegen::regalloc::coloring::Coloring::run
             at cranelift-codegen/src/regalloc/coloring.rs:152
  14: cranelift_codegen::regalloc::context::Context::run
             at cranelift-codegen/src/regalloc/context.rs:201
  15: cranelift_codegen::context::Context::regalloc
             at cranelift-codegen/src/context.rs:320
  16: cranelift_codegen::context::Context::compile
             at cranelift-codegen/src/context.rs:155
  17: cranelift_codegen::context::Context::compile_and_emit
             at cranelift-codegen/src/context.rs:112
  18: clif_util::compile::handle_module
             at src/compile.rs:70
  19: clif_util::compile::run
             at src/compile.rs:26
  20: clif_util::main
             at src/clif-util.rs:275
[...]
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bnjbvr** [comment]
Fixed by #1014 !
