### ISSUE TITLE
Regalloc fails with call_indirect on i686

### ISSUE THREAD

**Issue by bnjbvr** [CraneStation/cranelift#1074]
The following test case (extracted from Spidermonkey test suite and reduced with bugpoint) fails on i686.

Stack trace:

<details>

```
➜ RUST_BACKTRACE=1 cargo run compile -dDp  /tmp/b.clif
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/clif-util compile -dDp /tmp/b.clif`
thread 'main' panicked at 'assertion failed: !self.has_fixed_input_conflicts()', cranelift-codegen/src/regalloc/solver.rs:695:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:411
   8: cranelift_codegen::regalloc::solver::Solver::inputs_done
             at cranelift-codegen/src/regalloc/solver.rs:695
   9: cranelift_codegen::regalloc::coloring::Context::visit_inst
             at cranelift-codegen/src/regalloc/coloring.rs:472
  10: cranelift_codegen::regalloc::coloring::Context::visit_ebb
             at cranelift-codegen/src/regalloc/coloring.rs:193
  11: cranelift_codegen::regalloc::coloring::Context::run
             at cranelift-codegen/src/regalloc/coloring.rs:173
  12: cranelift_codegen::regalloc::coloring::Coloring::run
             at cranelift-codegen/src/regalloc/coloring.rs:152
  13: cranelift_codegen::regalloc::context::Context::run
             at cranelift-codegen/src/regalloc/context.rs:201
  14: cranelift_codegen::context::Context::regalloc
             at cranelift-codegen/src/context.rs:328
  15: cranelift_codegen::context::Context::compile
             at cranelift-codegen/src/context.rs:157
  16: cranelift_codegen::context::Context::compile_and_emit
             at cranelift-codegen/src/context.rs:113
  17: clif_util::compile::handle_module
             at src/compile.rs:70
  18: clif_util::compile::run
             at src/compile.rs:26
  19: clif_util::main
             at src/clif-util.rs:275
  20: std::rt::lang_start::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  21: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  22: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  23: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  24: std::panicking::try
             at src/libstd/panicking.rs:275
  25: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  26: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  27: std::rt::lang_start
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  28: main
  29: __libc_start_main
  30: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

Test case:

<details>

```
set probestack_enabled=false
target i686

function u0:0(i32 vmctx) baldrdash_system_v {
    sig0 = (i32 vmctx, i32 sigid) baldrdash_system_v

ebb0(v0: i32):
    v2 = iconst.i32 0
    v8 = iconst.i32 0
    v9 = iconst.i32 0
    call_indirect sig0, v8(v9, v2)
    trap user0
}
```
</details>

**Comment by bjorn3** [comment]
I assume those global values and the table are unnecessary for the crash?

**Comment by bjorn3** [comment]
bugpoint doesnt currently know about tables yet I believe.

**Comment by bnjbvr** [comment]
> I assume those global values and the table are unnecessary for the crash?

Thanks; I've edited the initial comment.

**Comment by bnjbvr** [comment]
Regalloc chooses to do a reassign_to into r10, which shouldn't be available on i686.
