### ISSUE TITLE
can't encode v22 = fill.i8 v0

### ISSUE THREAD

**Issue by bjorn3** [CraneStation/cranelift#477]
```clif
target i686

function u0:0(i8, i8) -> i8 fast {
    ss0 = explicit_slot 2
    ss1 = explicit_slot 2

ebb0(v0: i8, v1: i8):
    v2 = stack_addr.i32 ss0
    v5 = iadd.i8 v0, v1
    v7 = stack_addr.i32 ss1
    store v5, v7
    v16 = load.i8 v2
    return v16
}
```

Backtrace:

```
thread 'main' panicked at 'can't encode v22 = fill.i8 v0', lib/codegen/src/cursor.rs:760:23
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: std::panicking::try::do_call
             at libstd/panicking.rs:413
   7: <cranelift_codegen::regalloc::solver::Move as core::clone::Clone>::clone
             at lib/codegen/src/cursor.rs:760
   8: core::ptr::swap_nonoverlapping_bytes
             at lib/codegen/src/ir/builder.rs:132
   9: core::ptr::swap_nonoverlapping_bytes
             at ./target/debug/build/cranelift-codegen-11c4d82b599184bf/out/inst_builder.rs:1649
  10: core::ptr::swap_nonoverlapping_bytes
             at ./target/debug/build/cranelift-codegen-11c4d82b599184bf/out/inst_builder.rs:635
  11: cranelift_codegen::regalloc::reload::Context::visit_inst
             at lib/codegen/src/regalloc/reload.rs:219
  12: cranelift_codegen::regalloc::reload::Context::visit_ebb
             at lib/codegen/src/regalloc/reload.rs:130
  13: cranelift_codegen::regalloc::reload::Context::run
             at lib/codegen/src/regalloc/reload.rs:117
  14: cranelift_codegen::regalloc::reload::Reload::run
             at lib/codegen/src/regalloc/reload.rs:85
  15: cranelift_codegen::print_errors::pretty_function_error
             at lib/codegen/src/regalloc/context.rs:127
  16: <cranelift_codegen::settings::CallConv as core::cmp::PartialEq>::eq
             at lib/codegen/src/context.rs:294
  17: <cranelift_codegen::settings::CallConv as core::cmp::PartialEq>::eq
             at lib/codegen/src/context.rs:148
  18: <cranelift_codegen::settings::CallConv as core::cmp::PartialEq>::eq
             at lib/codegen/src/context.rs:101
  19: clif_util::compile::handle_module
             at src/compile.rs:103
  20: clif_util::compile::run
             at src/compile.rs:71
  21: clif_util::clif_util
             at src/clif-util.rs:118
  22: clif_util::main
             at src/clif-util.rs:154
[...]
```

**Comment by bjorn3** [comment]
@sunfishcode could you please give me instructions about how to fix this?

**Comment by sunfishcode** [comment]
I think for now it'd be good to just have `i8` and `i16` spills and fills copy what we do for `b1`, which is to use 32-bit load and store instructions:

https://github.com/CraneStation/cranelift/blob/master/lib/codegen/meta-python/isa/x86/encodings.py#L304
https://github.com/CraneStation/cranelift/blob/master/lib/codegen/meta-python/isa/x86/encodings.py#L322

That's not really optimal, but I think it's sufficient for now, and avoids the wrinkle that x86-32 doesn't support 8-bit stores from all registers.

I'm expecting in the future we'll add better framework support for i8 and i16, so that we don't always have to legalize them, and that'll make it easier to add i18 and i16 spill and fill encodings too.

**Comment by bjorn3** [comment]
Thanks!
