### ISSUE TITLE
fuzz: overflowing multiply

### ISSUE THREAD

**Issue by bnjbvr** [CraneStation/cranelift#607]
Haven't had time to investigate yet, but dropping here in case it's of interest to anybody :)

This [test case](https://benj.me/pub/multiply-with-overflow.wasm) (generated by binaryen) causes a panic at compilation (`cargo run wasm --target x86_64 test.wasm`) with the following message:

```
thread 'main' panicked at 'attempt to multiply with overflow', lib/codegen/src/divconst_magic_numbers.rs:106:18
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::panicking::panic
             at libcore/panicking.rs:52
   9: cranelift_codegen::divconst_magic_numbers::magicU64
             at lib/codegen/src/divconst_magic_numbers.rs:106
  10: cranelift_codegen::simple_preopt::do_divrem_transformation
             at lib/codegen/src/simple_preopt.rs:259
  11: cranelift_codegen::simple_preopt::do_preopt
             at lib/codegen/src/simple_preopt.rs:552
  12: cranelift_codegen::context::Context::preopt
             at lib/codegen/src/context.rs:221
  13: cranelift_codegen::context::Context::compile
             at lib/codegen/src/context.rs:121
  14: clif_util::wasm::handle_module
             at src/wasm.rs:168
  15: clif_util::wasm::run
             at src/wasm.rs:56
  16: clif_util::main
             at src/clif-util.rs:254
  17: std::rt::lang_start::{{closure}}
             at /rustc/25a42b2ceb46887e9941cec667eac99844dd7ad0/src/libstd/rt.rs:74
  18: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  19: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  20: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:398
             at libstd/rt.rs:58
  21: std::rt::lang_start
             at /rustc/25a42b2ceb46887e9941cec667eac99844dd7ad0/src/libstd/rt.rs:74
  22: main
  23: __libc_start_main
  24: _start
```

**Comment by bnjbvr** [comment]
Easy to reproduce actually: just call `magicU64(0x8000000000000001u64)` and see the crash. Ditto with the equivalent u32 value for `magicU32`.

@julian-seward1, can you have a look, please?
