### ISSUE TITLE
ebb without parameter causes panic

### ISSUE THREAD

**Issue by dlrobertson** [CraneStation/cranelift#609]
## Summary

The following test file causes a panic.

### `clif` file
```
test legalizer
target x86_64

function %ebb_no_param(i8) -> i8 {
ebb0:
    v1 = iconst.i32 42
    return v1
}
```

### panic
```
thread 'worker #0' panicked at 'internal error: entered unreachable code', lib/codegen/src/print_errors.rs:90:18
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::begin_panic
             at /rustc/ca79ecd6940e30d4b2466bf378632efcdf5745c7/src/libstd/panicking.rs:410
   6: cranelift_codegen::print_errors::pretty_instruction_error
             at lib/codegen/src/print_errors.rs:90
   7: <cranelift_codegen::print_errors::PrettyVerifierError<'a> as cranelift_codegen::write::FuncWriter>::write_instruction
             at lib/codegen/src/print_errors.rs:48
   8: cranelift_codegen::write::decorate_ebb
             at lib/codegen/src/write.rs:235
   9: cranelift_codegen::write::decorate_function
             at lib/codegen/src/write.rs:152
  10: cranelift_codegen::print_errors::pretty_verifier_error
             at lib/codegen/src/print_errors.rs:27
  11: cranelift_filetests::runone::run_one_test::{{closure}}
             at lib/filetests/src/runone.rs:133
  12: <core::result::Result<T, E>>::map_err
             at /rustc/ca79ecd6940e30d4b2466bf378632efcdf5745c7/src/libcore/result.rs:530
  13: cranelift_filetests::runone::run_one_test
             at lib/filetests/src/runone.rs:132
  14: cranelift_filetests::runone::run
             at lib/filetests/src/runone.rs:82
  15: cranelift_filetests::concurrent::worker_thread::{{closure}}::{{closure}}
             at lib/filetests/src/concurrent.rs:133
  16: std::panicking::try::do_call
             at /rustc/ca79ecd6940e30d4b2466bf378632efcdf5745c7/src/libstd/panicking.rs:310
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  18: std::panicking::try
             at /rustc/ca79ecd6940e30d4b2466bf378632efcdf5745c7/src/libstd/panicking.rs:289
  19: std::panic::catch_unwind
             at /rustc/ca79ecd6940e30d4b2466bf378632efcdf5745c7/src/libstd/panic.rs:398
  20: cranelift_filetests::concurrent::worker_thread::{{closure}}
             at lib/filetests/src/concurrent.rs:133
```

**Comment by sunfishcode** [comment]
Good catch! We should diagnose that in the verifier.

**Comment by dlrobertson** [comment]
Awesome! Re-tested and the correct error was reported.
