### ISSUE TITLE
How to use cranelift  build a function and call rust function？

### ISSUE THREAD

**Issue by mokeyish** [CraneStation/cranelift#675]
how to wrap add_impl as func_a

```rust
use cranelift::prelude::*;
use cranelift_module::{Linkage, Module};
use cranelift_simplejit::{SimpleJITBackend, SimpleJITBuilder};
use std::mem;

fn add_impl(a:i32, b: i32) -> i32 {
    a + b
}

fn main() {
    let mut module: Module<SimpleJITBackend> = Module::new(SimpleJITBuilder::new());
    let mut ctx = module.make_context();
    let mut func_ctx = FunctionBuilderContext::new();

    let mut sig_b = module.make_signature();
    sig_b.returns.push(AbiParam::new(types::I32));

    let func_b = module
        .declare_function("b", Linkage::Local, &sig_b)
        .unwrap();

    ctx.func.signature = sig_b;
    ctx.func.name = ExternalName::user(0, func_b.as_u32());
    {
        let mut bcx: FunctionBuilder = FunctionBuilder::new(&mut ctx.func, &mut func_ctx);
        let ebb = bcx.create_ebb();

        bcx.switch_to_block(ebb);

        // ????????????? how to wrap add_impl as func_a ?????
        let local_func = module.declare_func_in_func(func_a, &mut bcx.func);
        let arg = bcx.ins().iconst(types::I32, 5);
        let call = bcx.ins().call(local_func, &[arg]);
        let value = {
            let results = bcx.inst_results(call);
            assert_eq!(results.len(), 1);
            results[0].clone()
        };
        bcx.ins().return_(&[value]);
        bcx.seal_all_blocks();
        bcx.finalize();
    }
    module.define_function(func_b, &mut ctx).unwrap();
    module.clear_context(&mut ctx);

    // Perform linking.
    module.finalize_definitions();

    // Get a raw pointer to the generated code.
    let code_b = module.get_finalized_function(func_b);

    // Cast it to a rust function pointer type.
    let ptr_b = unsafe { mem::transmute::<_, fn() -> u32>(code_b) };

    // Call it!
    let res = ptr_b();

    assert_eq!(res, 42);
}
```

**Comment by bjorn3** [comment]
You could use https://github.com/CraneStation/cranelift/blob/c47ca7bafc8fc48358f1baa72360e61fc1f7a0f2/cranelift-simplejit/src/backend.rs#L64

**Comment by mokeyish** [comment]
@bjorn3 I still not know how to get funcId after defined the `add_impl` symbol

**Comment by bjorn3** [comment]
You then use `module.declare_function("func_name", Linkage::Local, &sig).unwrap();`.

**Comment by mokeyish** [comment]
@bjorn3 Here is my full code, It took an error.
```rust

use cranelift::prelude::*;
use cranelift_module::{Linkage, Module};
use cranelift_simplejit::{SimpleJITBackend, SimpleJITBuilder};
use std::mem;


fn add_impl(a:i32, b:i32) -> i32 {
    a + b
}

fn main() {

    let mut module: Module<SimpleJITBackend> = {
        let addr: *const u8 = unsafe { mem::transmute(&add_impl) };

        let mut jit_builder = SimpleJITBuilder::new();
        jit_builder.symbol("add_impl", addr);
        Module::new(jit_builder)
    };

    let mut ctx = module.make_context();
    let mut func_ctx = FunctionBuilderContext::new();

    let mut sig_a = module.make_signature();
    sig_a.params.push(AbiParam::new(types::I32));
    sig_a.params.push(AbiParam::new(types::I32));
    sig_a.returns.push(AbiParam::new(types::I32));

    let func_a = module
        .declare_function("add_impl", Linkage::Local, &sig_a)
        .unwrap();

//    ctx.func.signature = sig_a;
//    ctx.func.name = ExternalName::user(0, func_a.as_u32());
//    {
//        let mut bcx: FunctionBuilder = FunctionBuilder::new(&mut ctx.func, &mut func_ctx);
//
//        let ebb = bcx.create_ebb();
//
//        bcx.switch_to_block(ebb);
//        bcx.append_ebb_params_for_function_params(ebb);
//        let param_a = bcx.ebb_params(ebb)[0];
//        let param_b = bcx.ebb_params(ebb)[0];
//        let add = bcx.ins().iadd(param_a, param_b);
//        bcx.ins().return_(&[add]);
//        bcx.seal_all_blocks();
//
//        bcx.finalize();
//    }
//    module.define_function(func_a, &mut ctx).unwrap();
//    module.clear_context(&mut ctx);



    let mut sig_b = module.make_signature();
    sig_b.returns.push(AbiParam::new(types::I32));

    let func_b = module
        .declare_function("b", Linkage::Local, &sig_b)
        .unwrap();

    ctx.func.signature = sig_b;
    ctx.func.name = ExternalName::user(0, func_b.as_u32());

    {
        let mut bcx: FunctionBuilder = FunctionBuilder::new(&mut ctx.func, &mut func_ctx);
        let ebb = bcx.create_ebb();

        bcx.switch_to_block(ebb);
        let local_func = module.declare_func_in_func(func_a, &mut bcx.func);
        let arg_a = bcx.ins().iconst(types::I32, 5);
        let arg_b = bcx.ins().iconst(types::I32, 9);
        let call = bcx.ins().call(local_func, &[arg_a, arg_b]);
        let value = {
            let results = bcx.inst_results(call);
            assert_eq!(results.len(), 1);
            results[0].clone()
        };
        bcx.ins().return_(&[value]);
        bcx.seal_all_blocks();
        bcx.finalize();
    }
    module.define_function(func_b, &mut ctx).unwrap();
    module.clear_context(&mut ctx);

    // Perform linking.
    module.finalize_definitions();

    // Get a raw pointer to the generated code.
    let code_b = module.get_finalized_function(func_b);

    // Cast it to a rust function pointer type.
    let ptr_b = unsafe { mem::transmute::<_, fn() -> u32>(code_b) };

    // Call it!
    let res = ptr_b();

    println!("result:{}", res);
}
```

**Comment by bjorn3** [comment]
What error? It compiles fine.

**Comment by mokeyish** [comment]
```
   Compiling cranelift-simplejit v0.28.0 (/Users/yish/work/rust-work/cranelift-simplejit)
    Finished dev [unoptimized + debuginfo] target(s) in 1.50s
     Running `target/debug/examples/simplejit-minimal`
thread 'main' panicked at 'Finalization requires a definition for function u0:0.', /Users/yish/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-module-0.28.0/src/module.rs:276:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:340
   7: core::str::from_utf8_unchecked_mut
             at ./<::std::macros::panic macros>:8
   8: cranelift_simplejit::backend::SimpleJITBackend::lookup_symbol
             at src/backend.rs:312
   9: <cranelift_module::module::Module<B>>::finalize_definitions
             at /Users/yish/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-module-0.28.0/src/module.rs:630
  10: simplejit_minimal::main
             at examples/simplejit-minimal.rs:88
  11: std::rt::lang_start::{{closure}}
             at /rustc/f47ec2ad5b6887b3d400aee49e2294bd27733d18/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  13: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:87
  14: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/f47ec2ad5b6887b3d400aee49e2294bd27733d18/src/libstd/rt.rs:64
  16: simplejit_minimal::main
```

**Comment by bjorn3** [comment]
Wait I should have said module.declare_function("func_name", Linkage::**Import** &sig).unwrap();.

**Comment by mokeyish** [comment]
After I use `module.declare_function("func_name", Linkage::**Import** &sig).unwrap();`

Expect:
```
   Compiling cranelift-simplejit v0.28.0 (/Users/yish/work/rust-work/cranelift-simplejit)
    Finished dev [unoptimized + debuginfo] target(s) in 1.49s
     Running `target/debug/examples/simplejit-minimal`
result:10

Process finished with exit code 0
```

Actual :
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/examples/simplejit-minimal`

Process finished with exit code 138 (interrupted by signal 10: SIGBUS)
```

**Comment by bjorn3** [comment]
Could you attach a debugger for a backtrace?

**Comment by mokeyish** [comment]
My system is macos.

**Comment by mokeyish** [comment]
I didn't know how to solve this problem.
![image](https://user-images.githubusercontent.com/16131917/52899456-64edde00-3225-11e9-9971-b0b264e75f0e.png)

**Comment by bjorn3** [comment]
I  am trying to repro this now.

**Comment by bjorn3** [comment]
```diff
-        let addr: *const u8 = unsafe { mem::transmute(&add_impl) };
+        let addr: *const u8 = add_impl as *const u8;
```

Fixes the problem. `add_impl` has type `fn(i32, i32) -> i32 {add_impl}` which is a zero sized type specific for `add_impl`. When trying to take a reference to it, rustc will give a reference a stack slot of size 0.

**Comment by mokeyish** [comment]
It runs as expected.Thanks.
