### ISSUE TITLE
assertion failed: !self.opcode().is_branch() during licm

### ISSUE THREAD

**Issue by bjorn3** [CraneStation/cranelift#732]
Compile

```rust
// run-pass

// aux-build:xcrate-reachable.rs

#![feature(generator_trait)]

extern crate xcrate_reachable as foo;

use std::ops::Generator;
use std::pin::Pin;

fn main() {
    Pin::new(&mut foo::foo()).resume();
}
```

using rustc_codegen_cranelift with `opt_level=best` and you get:

```
---- [run-pass] run-pass/generator/xcrate-reachable.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit code: 101
command: "/home/bjorn/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc" "/home/bjorn/Documenten/rustc_codegen_cranelift/rust/src/test/run-pass/generator/xcrate-reachable.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-o" "/home/bjorn/Documenten/rustc_codegen_cranelift/rust/build/x86_64-unknown-linux-gnu/test/run-pass/generator/xcrate-reachable/a" "-Crpath" "-O" "-Zunstable-options" "-Zcodegen-backend=/home/bjorn/Documenten/rustc_codegen_cranelift/rust/../target/debug/librustc_codegen_cranelift.so" "--sysroot" "/home/bjorn/Documenten/rustc_codegen_cranelift/rust/../build_sysroot/sysroot" "-Cpanic=abort" "-Lnative=/home/bjorn/Documenten/rustc_codegen_cranelift/rust/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/bjorn/Documenten/rustc_codegen_cranelift/rust/build/x86_64-unknown-linux-gnu/test/run-pass/generator/xcrate-reachable/auxiliary"
stdout:
------------------------------------------
Instance { def: Item(DefId(9/1:10 ~ xcrate_reachable[8787]::foo[0]::{{closure}}[0])), substs: [(), u32, {()}] } _ZN16xcrate_reachable3foo28_$u7b$$u7b$closure$u7d$$u7d$17he526fe6105ca50ffE

------------------------------------------
stderr:
------------------------------------------
thread 'rustc' panicked at 'assertion failed: !self.opcode().is_branch()', /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/cadf244/cranelift-codegen/src/ir/instructions.rs:255:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   6: std::panicking::begin_panic
             at /rustc/474e7a6486758ea6fc761893b1a49cd9076fb0ab/src/libstd/panicking.rs:408
   7: cranelift_codegen::licm::do_licm
             at /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/cadf244/cranelift-codegen/src/ir/instructions.rs:255
             at /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/cadf244/cranelift-codegen/src/licm.rs:140
             at /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/cadf244/cranelift-codegen/src/licm.rs:89
             at /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/cadf244/cranelift-codegen/src/licm.rs:41
   8: cranelift_codegen::context::Context::compile
             at /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/cadf244/cranelift-codegen/src/context.rs:286
             at /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/cadf244/cranelift-codegen/src/context.rs:136
   9: cranelift_module::module::Module<B>::define_function
             at /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/cadf244/cranelift-module/src/module.rs:517
  10: rustc_codegen_cranelift::base::trans_fn
             at src/base.rs:202
  11: rustc_codegen_cranelift::base::trans_mono_item
             at src/base.rs:46
  12: rustc_codegen_cranelift::codegen_mono_items::{{closure}}::{{closure}}
             at src/lib.rs:473
  13: rustc_codegen_cranelift::unimpl::try_unimpl::{{closure}}
             at src/unimpl.rs:28
  14: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/474e7a6486758ea6fc761893b1a49cd9076fb0ab/src/libstd/panic.rs:309
  15: std::panicking::try::do_call
             at /rustc/474e7a6486758ea6fc761893b1a49cd9076fb0ab/src/libstd/panicking.rs:293
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  17: std::panicking::try
             at /rustc/474e7a6486758ea6fc761893b1a49cd9076fb0ab/src/libstd/panicking.rs:272
  18: std::panic::catch_unwind
             at /rustc/474e7a6486758ea6fc761893b1a49cd9076fb0ab/src/libstd/panic.rs:388
  19: rustc_codegen_cranelift::unimpl::try_unimpl
             at src/unimpl.rs:28
  20: rustc_codegen_cranelift::codegen_mono_items::{{closure}}
             at src/lib.rs:471
  21: rustc_codegen_cranelift::time
             at src/lib.rs:484
  22: rustc_codegen_cranelift::codegen_mono_items
             at src/lib.rs:469
  23: rustc_codegen_cranelift::codegen_cgus
             at src/lib.rs:456
  24: <rustc_codegen_cranelift::CraneliftCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
             at src/lib.rs:318
  25: rustc::util::common::time
  26: rustc_interface::passes::start_codegen
  27: rustc::ty::context::tls::enter_global
  28: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  29: rustc_interface::passes::create_global_ctxt::{{closure}}
  30: rustc_interface::passes::BoxedGlobalCtxt::enter
  31: rustc_interface::queries::Query<T>::compute
  32: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::ongoing_codegen
  33: rustc_interface::interface::run_compiler_in_existing_thread_pool
  34: std::thread::local::LocalKey<T>::with
  35: scoped_tls::ScopedKey<T>::set
  36: syntax::with_globals
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.35.0-nightly (474e7a648 2019-04-07) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z threads=1 -Z ui-testing -Z unstable-options -Z codegen-backend=/home/bjorn/Documenten/rustc_codegen_cranelift/rust/../target/debug/librustc_codegen_cranelift.so -C rpath -C panic=abort
```

**Comment by bjorn3** [comment]
The failing clif:

<details>

```
test compile
set is_pic
set opt_level=best
target x86_64-unknown-linux-gnu

function u0:0(i64, i64) system_v {
; symbol _ZN16xcrate_reachable3foo28_$u7b$$u7b$closure$u7d$$u7d$17he526fe6105ca50ffE
; instance Instance { def: Item(DefId(9/1:10 ~ xcrate_reachable[8787]::foo[0]::{{closure}}[0])), substs: [(), u32, {()}] }
; sig ([std::pin::Pin<&mut [generator@DefId(9/1:10 ~ xcrate_reachable[8787]::foo[0]::{{closure}}[0]) {()}]>]; c_variadic: false)->std::ops::GeneratorState<(), u32>

; ssa {_3: NOT_SSA, _0: NOT_SSA, _2: NOT_SSA, _1: NOT_SSA}
; msg   loc.idx    param    pass mode            ssa flags  ty
; ret    _0      = v0       ByRef                NOT_SSA    std::ops::GeneratorState<(), u32>
; arg    _1      = v1       ByVal(types::I64)    NOT_SSA    std::pin::Pin<&mut [generator@DefId(9/1:10 ~ xcrate_reachable[8787]::foo[0]::{{closure}}[0]) {()}]>
; zst    _2: () size=0 align=1, 8

    ss0 = explicit_slot 8 ; _1: std::pin::Pin<&mut [generator@DefId(9/1:10 ~ xcrate_reachable[8787]::foo[0]::{{closure}}[0]) {()}]> size=8 align=8,8
    ss1 = explicit_slot 4 ; _3: u32 size=4 align=4,4
    gv0 = symbol colocated u1:1
    gv1 = symbol colocated u1:2
    gv2 = symbol colocated u1:3
    sig0 = () -> i32 system_v
    sig1 = (i64) system_v
    sig2 = (i64) system_v
    sig3 = (i64) system_v
    fn0 = u0:7 sig0 ; Instance { def: Item(DefId(9/0:4 ~ xcrate_reachable[8787]::msg[0])), substs: [] }
    fn1 = u0:8 sig1
    fn2 = u0:8 sig2
    fn3 = u0:8 sig3
    jt0 = jump_table [ebb2, ebb5, ebb6, ebb4]

                                ebb0(v0: i64, v1: i64):
                                    v2 = stack_addr.i64 ss0
                                    store v1, v2
                                    v3 = iconst.i64 45
                                    v4 = stack_addr.i64 ss1
                                    jump ebb1

                                ebb1:
                                    nop 
; 
; switchInt(((*(_1.0: &mut [generator@DefId(9/1:10 ~ xcrate_reachable[8787]::foo[0]::{{closure}}[0]) {()}])).0: u32))
@0000                               v5 = load.i64 v2
@0000                               v6 = load.i32 v5
@0000                               jump ebb8

                                ebb8:
@0000                               br_table.i32 v6, ebb7, jt0

                                ebb2:
@0000                               nop 
; ((_0 as Yielded).0: ()) = move _2
@0001                               v7 = iadd_imm.i64 v0, 4
; discriminant(_0) = 0
@0001                               v8 = iconst.i32 0
@0001                               store v8, v0
; ((*(_1.0: &mut [generator@DefId(9/1:10 ~ xcrate_reachable[8787]::foo[0]::{{closure}}[0]) {()}])).0: u32) = const 3u32
@0001                               v9 = load.i64 v2
@0001                               v10 = iconst.i32 3
@0001                               store v10, v9
; 
; return
@0001                               return

                                ebb3:
@0001                               nop 
; ((_0 as Complete).0: u32) = move _3
@0002                               v11 = iadd_imm.i64 v0, 4
@0002                               v12 = load.i32 aligned v4
@0002                               store aligned v12, v11
; discriminant(_0) = 1
@0002                               v13 = iconst.i32 1
@0002                               store v13, v0
; ((*(_1.0: &mut [generator@DefId(9/1:10 ~ xcrate_reachable[8787]::foo[0]::{{closure}}[0]) {()}])).0: u32) = const 1u32
@0002                               v14 = load.i64 v2
@0002                               v15 = iconst.i32 1
@0002                               store v15, v14
; 
; return
@0002                               return

                                ebb4:
@0002                               nop 
; 
; _3 = const foo::msg()
@0004                               v16 = call fn0()
@0004                               store v16, v4
@0004                               jump ebb3

                                ebb5:
@0004                               nop 
; 
; assert(const false, "generator resumed after completion")
@0000                               v17 = iconst.i8 0
@0000                               v18 = uextend.i32 v17
@0000                               brnz v18, ebb5
@0000                               v19 = global_value.i64 gv0
@0000                               call fn1(v19)
@0000                               trap user0

                                ebb6:
@0000                               nop 
; 
; assert(const false, "generator resumed after panicking")
@0000                               v20 = iconst.i8 0
@0000                               v21 = uextend.i32 v20
@0000                               brnz v21, ebb6
@0000                               v22 = global_value.i64 gv1
@0000                               call fn2(v22)
@0000                               trap user0

                                ebb7:
@0000                               nop 
; 
; unreachable
@0000                               v23 = global_value.i64 gv2
@0000                               call fn3(v23)
@0000                               trap user65535
}
```

</details>

**Comment by bjorn3** [comment]
Minimal repro:

```
test compile
set is_pic
set opt_level=best
target x86_64

function u0:0(i64) system_v {
    jt0 = jump_table [ebb2, ebb5]

                                ebb0(v0: i64):
@0000                               br_table.i64 v0, ebb7, jt0

                                ebb2:
@0001                               return

                                ebb5:
@0000                               v18 = iconst.i32 0
@0000                               jump ebb5

                                ebb7:
@0000                               trap user65535
}
```

Backtrace:

```
   5: std::panicking::begin_panic
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/panicking.rs:412
   6: cranelift_codegen::ir::instructions::InstructionData::branch_destination_mut
             at cranelift-codegen/src/ir/instructions.rs:255
   7: cranelift_codegen::licm::change_branch_jump_destination
             at cranelift-codegen/src/licm.rs:142
   8: cranelift_codegen::licm::create_pre_header
             at cranelift-codegen/src/licm.rs:91
   9: cranelift_codegen::licm::do_licm
             at cranelift-codegen/src/licm.rs:43
  10: cranelift_codegen::context::Context::licm
             at cranelift-codegen/src/context.rs:286
  11: cranelift_codegen::context::Context::compile
             at cranelift-codegen/src/context.rs:136
```

**Comment by jgouly** [comment]
`branch_destination` and `branch_destination_mut` disagree a bit :)

https://github.com/CraneStation/cranelift/blob/master/cranelift-codegen/src/ir/instructions.rs#L219
https://github.com/CraneStation/cranelift/blob/master/cranelift-codegen/src/ir/instructions.rs#L253

**Comment by sunfishcode** [comment]
@jgouly Good catch! That does look likely to be the immediate issue here.

That said, if that's fixed, and `branch_destination_mut` returns `None`, [this code in LICM](https://github.com/CraneStation/cranelift/blob/master/cranelift-codegen/src/licm.rs#L142) will just silently ignores the instruction, which isn't ok if it needs to rewrite branches to [insert a loop preheader](https://github.com/CraneStation/cranelift/blob/master/cranelift-codegen/src/licm.rs#L64). I think we either need to bail out trying to create a preheader in the presence of an indirect jump earlier, or teach LICM how to modify indirect jump tables as needed.

**Comment by tyler** [comment]
@sunfishcode 
Oy. I'm pretty sure this one was my fault, that divergence happened during jump table implementation.

I'd like to try to fix this by teaching LICM to modify jump tables. Which, I think should be something like:

Get the necessary info with `analyze_branch`.
If it's a single destination, do what we do now.
If it's a table, swap each entry in the table pointing at `header` to point at `preheader`.

Is that roughly correct?
