### ISSUE TITLE
thread 'main' panicked at 'assertion failed: new_info == info'

### ISSUE THREAD

**Issue by ash-tamraz** [CraneStation/cranelift#792]
Running this on Ubuntu 16.04.6 on an x86_64 machine.

While in my fork that is even with `CraneStation:master`, on a branch with no changes, running `cargo run compile -p --target=x86_64 filetests/wasm/i64-compares.clif` produces the output:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/clif-util compile -p --target=x86_64 filetests/wasm/i64-compares.clif`
thread 'main' panicked at 'assertion failed: new_info == info', cranelift-codegen/src/context.rs:109:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::begin_panic
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libstd/panicking.rs:412
   6: cranelift_codegen::context::Context::compile_and_emit
             at cranelift-codegen/src/context.rs:109
   7: clif_util::compile::handle_module
             at src/compile.rs:68
   8: clif_util::compile::run
             at src/compile.rs:26
   9: clif_util::main
             at src/clif-util.rs:248
  10: std::rt::lang_start::{{closure}}
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libstd/rt.rs:64
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  13: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  14: std::rt::lang_start
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libstd/rt.rs:64
  15: main
  16: __libc_start_main
  17: _start
```

and running `cargo run wasm -v -p --target=x86_64 wasmtests/arith.wat` produces the output:

```
     Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/clif-util wasm -p --target=x86_64 wasmtests/arith.wat`
thread 'main' panicked at 'assertion failed: new_info == info', cranelift-codegen/src/context.rs:109:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::begin_panic
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libstd/panicking.rs:412
   6: cranelift_codegen::context::Context::compile_and_emit
             at cranelift-codegen/src/context.rs:109
   7: clif_util::wasm::handle_module
             at src/wasm.rs:179
   8: clif_util::wasm::run
             at src/wasm.rs:58
   9: clif_util::main
             at src/clif-util.rs:267
  10: std::rt::lang_start::{{closure}}
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libstd/rt.rs:64
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  13: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  14: std::rt::lang_start
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libstd/rt.rs:64
  15: main
  16: __libc_start_main
  17: _start
```

@lars-t-hansen

**Comment by lars-t-hansen** [comment]
This repros easily on my mac too.

**Comment by lars-t-hansen** [comment]
The two structures have different rodata_size values so they are indeed non-equal.

**Comment by bnjbvr** [comment]
Fixed by https://github.com/CraneStation/cranelift/pull/797.

**Comment by ash-tamraz** [comment]
Thanks @lars-t-hansen !
